### ISSUE TITLE
[meta issue]create mix header 

### ISSUE THREAD

**Issue by gpestana** [hashmatter/p3lib#6]
This is a rather large task and comprises almost all the work for this lib.

- [x] define packet structure 
- [x] generate ECDH shared secret (crypto, individual pairs)
- [x] generate fillers for each header
- [x] generate shared keys for a given circuit 
- [x] generate blinding factors
- [x] packet MAC

**Comment by gpestana** [comment]
This is done, although it still needs to be thoroughly tested (being worked on #14)
